API_HOST_URL: 'https://courses.prometheus.org.ua/' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'Prod Server'
PLATFORM_NAME: 'Prometheus'
PLATFORM_DESTINATION_NAME: 'prometheus.org.ua'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
USER_PROFILES_ENABLED: true
DISCUSSIONS_ENABLED: true
CERTIFICATES_ENABLED: true
NEW_LOGISTRATION_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true,
VIDEO_TRANSCRIPT_ENABLED: true,
BADGES_ENABLED: true,
"COURSE_ENROLLMENT": {
    "TYPE": "native"
}
FABRIC: {
  ENABLED: true,
  FABRIC_KEY: "013155ba3de2508e862ee784e2d646bcb76eb7d5",
  FABRIC_BUILD_SECRET: "840b47e08fcd996e1449f0fa7797c084595b82d31241cd90e35ba651ba61344b",
  KITS: {
    CRASHLYTICS: true,
    ANSWERS: true
  }
}
SPEED_TEST_ENABLED: false
APP_REVIEWS_ENABLED: true