API_HOST_URL: 'http://prometheus-test-server.cloudapp.net' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'Localhost'
PLATFORM_NAME: 'Prometheus'
PLATFORM_DESTINATION_NAME: 'prometheus-test-server.cloudapp.net;'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
COURSE_ENROLLMENT : {
  TYPE: 'native',
  WEBVIEW: {
    COURSE_SEARCH_URL: 'http://prometheus-test-server.cloudapp.net/courses?type=mobile',
    COURSE_INFO_URL_TEMPLATE: 'http://prometheus-test-server.cloudapp.net/courses/{path_id}',
    SEARCH_BAR_ENABLED: true
  }
}
USER_PROFILES_ENABLED: true
DISCUSSIONS_ENABLED: true
CERTIFICATES_ENABLED: true
NEW_LOGISTRATION_ENABLED: true
OAUTH_CLIENT_ID: 'e0dda1692c35b0986297'