API_HOST_URL: ' https://courses.prometheus.org.ua/' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'Prod Server'
PLATFORM_NAME: 'Prometheus'
PLATFORM_DESTINATION_NAME: 'prometheus.org.ua'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
COURSE_ENROLLMENT : {
  TYPE: 'native'
}
USER_PROFILES_ENABLED: true
DISCUSSIONS_ENABLED: true
CERTIFICATES_ENABLED: true
NEW_LOGISTRATION_ENABLED: true
OAUTH_CLIENT_ID: '98102d634d933574d018'