API_HOST_URL: 'http://prometheus-test-server.cloudapp.net' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'Test Server'
PLATFORM_NAME: 'Prometheus'
PLATFORM_DESTINATION_NAME: 'prometheus-test-server.cloudapp.net;'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
COURSE_ENROLLMENT : {
  TYPE: 'native'
}
FABRIC: {
    ENABLED: true,
    FABRIC_KEY: "013155ba3de2508e862ee784e2d646bcb76eb7d5",
    BUILD_SECRET: "840b47e08fcd996e1449f0fa7797c084595b82d31241cd90e35ba651ba61344b"
}
USER_PROFILES_ENABLED: true
DISCUSSIONS_ENABLED: true
CERTIFICATES_ENABLED: true
NEW_LOGISTRATION_ENABLED: true
OAUTH_CLIENT_ID: 'e0dda1692c35b0986297'